### ISSUE TITLE
Publish versioned binaries in github releases

### ISSUE THREAD

**Issue by aabmass** [googleinterns/cloud-operations-api-mock#47]

**Comment by aabmass** [comment]
@mabdi3 would you be able to do this?

**Comment by mabdi3** [comment]
> @mabdi3 would you be able to do this?

Is something like this what you had in mind? https://github.com/googleinterns/cloud-operations-api-mock/releases/tag/v0-alpha

**Comment by aabmass** [comment]
Yup, thank you!
